apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalmetrics.metrics.newrelic
spec:
  group: metrics.newrelic
  version: v1alpha1
  names:
    kind: ExternalMetric
    plural: externalmetrics
    singular: externalmetric
  scope: Namespaced
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-newrelic-adapter:crd-metrics-reader
  labels:
    app: k8s-newrelic-adapter
rules:
- apiGroups:
  - metrics.newrelic
  resources:
  - "externalmetrics"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-newrelic-adapter:crd-metrics-reader
  labels:
    app: k8s-newrelic-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-newrelic-adapter:crd-metrics-reader
subjects:
  - name: k8s-newrelic-adapter
    namespace: newrelic-custom-metrics
    kind: ServiceAccount
